package com.android.luggshare.common.keys;

public class AppConstants {

    //length of edit texts

    public static final int BOTTOMSHEET_PLACE = 224;
    public static final int BOTTOMSHEET_SCHEDULED = 152;
    public static final int BOTTOMSHEET_LATER = 268;
    public static final String CURRENCY_UNIT = "$";
    public static final String KEY_PHONE = "phone";
    public static final String KEY_SOCIAL_MEDIA_TYPE = "social_type";
    public static final String KEY_FB_ID = "facebook_id";
    public static final String KEY_SOCIAL_ID = "social_id";
    public static final String KEY_SOCIAL_NAME = "social_name";
    public static final String KEY_SOCIAL_PASSWORD = "social_password";
    public static final String KEY_SOCIAL_PHONE = "social_phone";
    public static final String KEY_SOCIAL_EMAIL = "social_email";
    public static final String KEY_SOCIAL_ACCESS_TOKEN = "social_access_token";
    public static final String KEY_SOCIAL_IMAGE_URL = "social_image_url";
    public static final String KEY_RANDOM_NO = "random_number";
    public static final String KEY_GOOGLE_ID = "google_id";
    public static final String KEY_FIRST_NAME = "first_name";
    public static final String KEY_LAST_NAME = "last_name";
    public static final String KEY_EMAIL = "email";
    public static final String KEY_PASSWORD = "password";
    public static final String KEY_GENDER = "gender";
    public static final String KEY_BIRTHDAY = "birthday";
    public static final String KEY_LOCATION = "location";
    public static final String KEY_FACEBOOK = "Facebook";
    public static final String KEY_GOOGLE = "Google";
    public static final String KEY_LATITUDE = "Latitude";
    public static final String KEY_LONGITUDE = "Longitude";
    public static final String KEY_TYPE = "Type";
    public static final String KEY_ADDRESS = "LocationAddress";
    public static final String KEY_PICKUP_LATITUDE = "pickup_latitude";
    public static final String KEY_PICKUP_LONGITUDE = "pickup_longitude";
    public static final String KEY_PICKUP_POSTAL_CODE = "pickup_postal_code";
    public static final String KEY_DROP_OFF_LATITUDE = "dropoff_latitude";
    public static final String KEY_DROP_OFF_LONGITUDE = "dropoff_longitude";
    public static final String KEY_DROP_OFF_POSTAL_CODE = "dropoff_postal_code";
    public static final String KEY_DESTINATION_LATER = "destination_later";
    public static final String KEY_TOTAL_DISTANCE = "total_distance";
    public static final String KEY_TOTAL_FARE = "total_fare";
    public static final String KEY_CAR_TYPE = "car_type";
    public static final String KEY_CAR_TYPE_ID = "car_type_id";
    public static final String KEY_JOB_TIME_STAMP = "job_time_stamp";
    public static final String KEY_TIME_DROP_OFF = "time_drop_off";
    public static final String KEY_JOB_COMPANY_NAME = "job_company_name";
    public static final String KEY_JOB_COMPANY_PHONE = "job_company_phone";
    public static final String KEY_JOB_DRIVER_ID = "job_driver_id";
    public static final String KEY_JOB_DRIVER_LOCATION = "job_driver_location";
    public static final String KEY_JOB_DRIVER_LATITUDE = "job_driver_latitude";
    public static final String KEY_JOB_DRIVER_LONGITUDE = "job_driver_longitude";
    public static final String KEY_JOB_DRIVER_NAME = "job_driver_name";
    public static final String KEY_JOB_DRIVER_RATING = "job_driver_rating";
    public static final String KEY_JOB_DRIVER_RATING_ID = "job_driver_rating_id";
    public static final String KEY_JOB_DRIVER_STATUS = "job_driver_status";
    public static final String KEY_JOB_DRIVER_PICTURE = "job_driver_picture";
    public static final String KEY_JOB_NUMBER = "job_number";
    public static final String KEY_JOB_STATUS = "job_status";
    public static final String KEY_JOB_VEHICLE_COLOR = "job_vehicle_color";
    public static final String KEY_JOB_VEHICLE_ID = "job_vehicle_id";
    public static final String KEY_JOB_VEHICLE_MAKE = "job_vehicle_make";
    public static final String KEY_SUB_TOTAL = "sub_total";
    public static final String KEY_TOTAL = "total";
    public static final String KEY_JOB_VEHICLE_MODEL = "job_vehicle_model";
    public static final String KEY_JOB_VEHICLE_REG_ID = "job_vehicle_reg_id";
    public static final String KEY_JOB_VEHICLE_SEATS = "job_vehicle_seats";
    public static final String KEY_JOB_VEHICLE_TYPE = "job_vehicle_type";
    public static final String KEY_JOB_VEHICLE_TYPE_ID = "job_vehicle_type_id";
    public static final String KEY_JOB_COMPANY_ID = "job_company_id";
    public static final String KEY_DROP_OFF_ADDRESS = "drop_off_address";
    public static final String KEY_PICK_UP_ADDRESS = "pick_up_address";
    public static final String KEY_FARE = "fare";
    public static final String KEY_ETA = "eta";
    public static final String KEY_USER_IMAGE = "user_image";
    public static final String KEY_USER_IMAGE_EXTENSION = "user_image_extension";
    public static final String KEY_IS_RIDE_LATER = "is_ride_later";
    public static final String KEY_RIDE_LATER_DATE = "ride_later_date";
    public static final String KEY_RIDE_LATER_TIME = "ride_later_time";
    public static final String KEY_RIDE_LATER_DATE_TIME = "ride_later_date_time";
    public static final Integer COMPANY_ID = 15;
    public static final String BASE_URL = "http://stage.infocabs.com:816/api/";
    public static final String KEY_REASON = "reason";
    public static final String KEY_SELECTED_CARD_ID = "card_id";
    public static final String KEY_SELECTED_CARD_TYPE = "card_type";
    public static final String KEY_SELECTED_CARD_NUMBER = "card_number";
    public static final String KEY_IS_JOB_ACTIVE = "is_job_active";
    public static final String KEY_CAR_NAME = "car_name";
    public static final String KEY_NOTES = "notes";
    public static final String KEY_SENDER = "sender";
    public static final String KEY_TRAVELER = "traveler";
    public static final String KEY_PURCHASER = "purchaser";

    public static final String KEY_SENDER_NAME = "name";
    public static final String KEY_SENDER_DESC = "description";
    public static final String KEY_SENDER_WEIGHT = "weight";
    public static final String KEY_SENDER_SIZE = "size";
    public static final String KEY_SENDER_FROM_COUNTRY = "from_country";
    public static final String KEY_SENDER_FROM_CITY = "from_city";
    public static final String KEY_SENDER_TO_COUNTRY = "to_country";
    public static final String KEY_SENDER_TO_CITY = "to_city";
    public static final String KEY_SENDER_DEL_DATE = "delivery_date";
    public static final String KEY_TRAVELER_DEP_DATE = "departure_date";
    public static final String KEY_TRAVELER_ARV_DATE = "arrival_date";
    public static final String KEY_TRAVELER_CAPACITY = "capacity";
    public static final String KEY_SENDER_ITEM_1 = "item_1";
    public static final String KEY_SENDER_ITEM_2 = "item_2";
    public static final String KEY_SENDER_ITEM_3 = "item_3";
    public static final String KEY_SENDER_ITEM_4 = "item_4";
    public static final String KEY_SENDER_ITEM_5 = "item_5";
    public static final String KEY_SENDER_ITEM_6 = "item_6";
    public static final String KEY_IMAGE_1 = "img1";
    public static final String KEY_IMAGE_1_EXTENSION = "img_1_extension";
    public static final String KEY_IMAGE_2 = "img2";
    public static final String KEY_IMAGE_2_EXTENSION = "img_2_extension";
    public static final String KEY_TRAVELER_OBJECT = "traveler_object";


    public static final String KEY_PURCHASER_URL = "url";
    public static final String KEY_PURCHASER_NAME = "prod_name";
    public static final String KEY_PURCHASER_DESC = "prod_detail";
    public static final String KEY_PURCHASER_PRICE = "price";
    public static final String KEY_PURCHASER_QUANT = "quantity";
    public static final String KEY_PURCH_IMAGE_1 = "img1";
    public static final String KEY_PURCH_IMAGE_1_EXTENSION = "img_1_extension";
    public static final String KEY_PURCH_FROMCOUNTRY = "from_country";
    public static final String KEY_PURCH_FROMCITY = "from_city";
    public static final String KEY_PURCH_TOCOUNTRY = "to_country";
    public static final String KEY_PURCH_TOCITY = "to_city";
    public static final String KEY_PURCH_DELDATE = "del_date";
    public static final String KEY_DELVCHARGES_EDT = "edt_delvcharges";

    public static final String KEY_USER_FNAME = "fname";
    public static final String KEY_USER_LNAME = "fname";
    public static final String KEY_USER_EMAIL = "email";
    public static final String KEY_USER_PASS = "pass";
    public static final String KEY_USER_COUNTRY = "country";
    public static final String KEY_USER_CITY = "city";
    public static final String KEY_USER_PROFIMAGE = "user_image";

    //public static final String BASE_IMG_PATH = "http://tnssuet.com.192-185-7-212.hgws27.hgwin.temp.domains/images/";

    public static final String BASE_IMG_PATH = "http://luggshare-001-site1.htempurl.com/images/";

}
